#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
	print "only the parameter of input file name should be passed."
	sys.exit(0)
try:
	inputfile = open(sys.argv[1], 'r')
except IOError as e:
	print "Cannot open input file. Error message : {0}".format(e.strerror)
	exit(0)
try:
	max_name, max_gc_index = "", 0
	buf = inputfile.readline().rstrip("\r\n")
	while len(buf)>0:
		sequence_name, sequence_includes, sequence_length = buf[1:], 0 , 0
		buf = inputfile.readline().rstrip("\r\n")
		while not buf.startswith('>') and len(buf)>0:
			sequence_length += len(buf)
			for char in buf:
				if char == 'C' or char == 'G':
					sequence_includes +=1
			buf = inputfile.readline().rstrip("\r\n")
		if(sequence_includes/float(sequence_length) > max_gc_index):
			max_gc_index = sequence_includes/float(sequence_length)
			max_name = sequence_name
	print('%s\n%.6f%%' % (max_name, max_gc_index*100))
except IOError as e:
	print "Cannot read input file. Error message : {0}".format(e.strerror)
	exit(0)
finally:
	inputfile.close()
