#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
	print "only the parameter of input file name should be passed."
	sys.exit(0)
try:
	inputfile = open(sys.argv[1], 'r')
except IOError as e:
	print "Cannot open input file. Error message : {0}".format(e.strerror)
	exit(0)
try:
	maxindex = 0.0
	maxname = ""
	curindex = 0.0
	curdnalength = 1
	curname = ""
	for line in inputfile:
		line = line.rstrip("\r\n")
		if line[0] == '>':
			curindex = curindex*100/curdnalength
			if curindex > maxindex:
				maxindex = curindex
				maxname = curname
			curname = line[1:]
			curdnalength = 0
			curindex = 0
		else:
			curdnalength+=len(line)
			for char in line:
				if char == 'G' or char == 'C':
					curindex+=1.0
	curindex = curindex*100/curdnalength
	if curindex > maxindex:
		maxindex = curindex
		maxname = curname
	print maxname
	print str(round(maxindex, 6)) + "%"
except IOError as e:
	print "Cannot read input file. Error message : {0}".format(e.strerror)
	exit(0)
finally:
	inputfile.close()
