#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
	print "only the parameter of input file name should be passed."
	sys.exit(0)
try:
	inputfile = open(sys.argv[1], 'r')
except IOError as e:
	print "Cannot open input file. Error message : {0}".format(e.strerror)
	exit(0)
try:
	buf = inputfile.readline().rstrip("\r\n")
	dnas = {}
	while buf:
		dna_name, dna_string= buf[1:], ""
		buf = inputfile.readline().rstrip("\r\n")
		while not buf.startswith('>') and buf:
			dna_string += buf
			buf = inputfile.readline().rstrip("\r\n")
		dnas[dna_name] = dna_string
except IOError as e:
	print "Cannot read input file. Error message : {0}".format(e.strerror)
	exit(0)
finally:
	inputfile.close()
for cur_key ,cur_value in dnas.items():
	for iterating_key, iterating_value in dnas.items():
		if not cur_key == iterating_key:
			if cur_value[-3:] == iterating_value[:3]:
				print cur_key, iterating_key
