#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
	print "only the parameter of input file name should be passed."
	sys.exit(0)
try:
	inputfile = open(sys.argv[1], 'r')
except IOError as e:
	print "Cannot open input file. Error message : {0}".format(e.strerror)
	exit(0)
try:
	line = inputfile.readline()
except IOError as e:
	print "Cannot read input file. Error message : {0}".format(e.strerror)
	exit(0)
finally:
	inputfile.close()
print line.replace('A','t').replace('T','a').replace('G','c').replace('C','g').upper()[::-1]
