#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
	print "only the parameter of input file name should be passed."
	sys.exit(0)
try:
	inputfile = open(sys.argv[1], 'r')
except IOError as e:
	print "Cannot open input file. Error message : {0}".format(e.strerror)
	exit(0)
try:
	line = inputfile.readline().rstrip("\r\n")
	subline = inputfile.readline().rstrip("\r\n")
except IOError as e:
	print "Cannot read input file. Error message : {0}".format(e.strerror)
	exit(0)
finally:
	inputfile.close()
i=0
while i<len(line):
    i=line.find(subline, i)+1
    if i == 0:
        break
    print i , " ",
